#:schema node_modules/wrangler/config-schema.json
name = "oidc-github-actions-worker"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]
workers_dev = false
preview_urls = false
kv_namespaces = [
    { binding = "KV", id = "8065f6815b8b4d1ba62066d387f0b7d2"}
]

[env.production]
logpush = true
workers_dev = false
preview_urls = false
upload_source_maps = true
kv_namespaces = [
    { binding = "KV", id = "18936835d1434580957a15f3e14628e7"}
]
routes = [
    {pattern = "github-oidc-worker.cyberjake.xyz", custom_domain=true }
]



[env.production.observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[env.production.observability.traces]
enabled = true
destinations = [ "grafana-cloud-tempo" ]
persist = true
head_sampling_rate = 1


